### ISSUE TITLE
Dark theme code block - low visibility

### ISSUE THREAD

**Issue by dac73** [openSUSE/jekyll-theme#25]
![Screenshot_20200716_151541](https://user-images.githubusercontent.com/20690019/87675096-3b691700-c777-11ea-9549-1f5d945441a3.png)

**Comment by guoyunhe** [comment]
To solve the issue on kernel.opensuse.org, you have to rebuilt the site:

```
bundle update
bundle exec jekyll build
```

**Comment by hellcp** [comment]
It will rebuild itself on the next commit anyway
