### ISSUE TITLE
_layouts/default.html fails verification

### ISSUE THREAD

**Issue by lrupp** [openSUSE/jekyll-theme#27]
Just have a look at the output of: https://validator.w3.org/nu/?doc=https%3A%2F%2Fmonitor.opensuse.org%2F

Error: Attribute xmlns:og not allowed here.

**Comment by hellcp** [comment]
According to https://stackoverflow.com/a/8339047 we can do nothing about it, so let's just agree to ignore it :P

**Comment by guoyunhe** [comment]
More errors on news.opensuse.org https://validator.w3.org/nu/?doc=https%3A%2F%2Fnews.opensuse.org
